=== chrismeller/siteml/SiteML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (x64) (http://www.altova.com) by User (Company) -->
<!--W3C Schema generated by XMLSpy v2013 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:attribute name="version" type="xs:string"/>
	<xs:attribute name="key" type="xs:string"/>
	<xs:attribute name="id" type="xs:integer"/>
	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="user">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="email"/>
				<xs:element ref="date-created"/>
				<xs:element ref="extended-properties" minOccurs="0"/>
				<xs:element ref="url" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute ref="id" use="required">
				<xs:annotation>
					<xs:documentation>A numeric identifier used to reference this element elsewhere in the export. You SHOULD NOT use this anywhere outside of this export - absolutely not as any sort of auto increment field in a database.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="url" type="xs:anyURI"/>
	<xs:element name="title" type="xs:string"/>
	<xs:element name="site">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="date-created"/>
				<xs:element ref="generator"/>
				<xs:element ref="url"/>
				<xs:element ref="title"/>
				<xs:element ref="extended-properties" minOccurs="0"/>
				<xs:element ref="users"/>
				<xs:element name="posts">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="post" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="title"/>
										<xs:element name="body" type="xs:string"/>
										<xs:element ref="date-created"/>
										<xs:element ref="extended-properties" minOccurs="0"/>
										<xs:element name="authors">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="author" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute ref="id" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="date-modified" type="xs:dateTime" minOccurs="0"/>
										<xs:element ref="url" minOccurs="0"/>
										<xs:element name="comments" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="comment" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="author">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element ref="email" minOccurs="0"/>
																			<xs:element name="url" minOccurs="0"/>
																			<xs:element name="name"/>
																			<xs:element name="ip" minOccurs="0"/>
																			<xs:element ref="extended-properties" minOccurs="0"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="body"/>
																<xs:element ref="date-created"/>
																<xs:element name="date-modified" minOccurs="0"/>
															</xs:sequence>
															<xs:attribute ref="id" use="required"/>
															<xs:attribute name="type" type="xs:string" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="taxonomy" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="vocabulary">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="term" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute ref="id" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute ref="id" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute ref="id" use="required"/>
									<xs:attribute name="type" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="taxonomy" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vocabulary" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="name"/>
										<xs:element ref="url" minOccurs="0"/>
										<xs:element name="terms">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="term" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element ref="name"/>
																<xs:element ref="url" minOccurs="0"/>
																<xs:element ref="extended-properties" minOccurs="0"/>
															</xs:sequence>
															<xs:attribute ref="id" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element ref="extended-properties" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute ref="id" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="key" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="generator">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="version" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="extended-properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="email" type="xs:string"/>
	<xs:element name="date-created" type="xs:dateTime"/>
</xs:schema>

=== chrismeller/siteml/SiteML.xml
<?xml version="1.0" encoding="UTF-8"?>
<site xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SiteML.xsd">
  <date-created>2001-12-17T09:30:47Z</date-created>
	<generator version="0.10">Habari</generator>
	<url>http://blog.chrismeller.com</url>
	<title>Chris Meller</title>
	<users>
		<user id="1">
			<name>chris</name>
			<email>chris@doesnthaveone.com</email>
			<date-created>2001-12-17T09:30:47Z</date-created>
			<extended-properties>
				<property key="first-name">Chris</property>
				<property key="last-name">Meller</property>
			</extended-properties>
			<url>http://blog.chrismeller.com</url>
		</user><user id="2">
			<name>foo</name>
			<email>foo@example.com</email>
			<date-created>2001-12-17T09:30:47Z</date-created>
		</user>
	</users>
	<content>
		<item id="1" type="post">
			<title>Welcome to Habari</title>
			<body>Welcome to your example Habari blog!</body>
			<date-created>2001-12-17T09:30:47Z</date-created>
			<authors>
				<author id="1"/>
				<author id="2"/>
			</authors>
			<url>welcome-to-habari</url>
			<taxonomy>
				<vocabulary id="1">
					<term id="1"></term>
				</vocabulary>
			</taxonomy>
		</item>
		<item id="2" type="page">
			<title>Example Page</title>
			<body>This is a page</body>
			<date-created>2001-12-17T09:30:47Z</date-created>
			<authors>
				<author id="1"></author>
			</authors>
			<url>example-page</url>
		</item>
	</content>
	<taxonomy>
		<vocabulary id="1">
			<name>Tags</name>
			<terms>
				<term id="1">
					<name>Foo</name>
					<url>foo</url>
				</term>
				<term id="2">
					<name>Bar</name>
					<url>bar</url>
					<extended-properties>
						<property key="parent-term-id">1</property>
					</extended-properties>
				</term>
			</terms>
			<extended-properties>
				<property key="type">hierarchical</property>
			</extended-properties>
		</vocabulary>
	</taxonomy>
</site>
